import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "@/styles/globals.css";
import Providers from "./providers";

// Classic arcade pixel font for diegetic HUD bits (the exit prompt). Exposed as
// a CSS variable; next/font self-hosts it at build time, so it ships with the
// static export — no runtime network fetch.
const retro = Press_Start_2P({
  variable: "--font-retro",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${retro.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
